### ISSUE TITLE
Migrate to version catalogs (gradle)

### ISSUE THREAD

**Issue by kasem-sm** [kasem-sm/SlimeKT#155]

**Comment by indyfromoz** [comment]
@kasem-sm For this issue, is the plan to use TOML format for version catalogs and structure the dependencies? If that is correct and if you are accepting #hackroberfest submissions, may I be assigned this issue?

**Comment by kasem-sm** [comment]
Hi @indyfromoz. Yep, plain TOML format file.
If you need a real world example, let me know. Till then you can refer [this ](https://docs.gradle.org/current/userguide/platforms.html#:~:text=For%20example%3A-,The%20libs.versions.toml%20file,-%5Bversions%5D%0Agroovy%20%3D%20%223.0.5)link 😊

**Comment by indyfromoz** [comment]
Thanks @kasem-sm!

I was reading up on TOML via the official docs you linked and [this Blog post](https://proandroiddev.com/gradle-version-catalogs-for-an-awesome-dependency-management-f2ba700ff894).

If you are okay for me start on the task, please feel free to assign it to me.

**Comment by kasem-sm** [comment]
done 👍 

> Thanks @kasem-sm!
> 
> I was reading up on TOML via the official docs you linked and [this Blog post](https://proandroiddev.com/gradle-version-catalogs-for-an-awesome-dependency-management-f2ba700ff894).
> 
> If you are okay for me start on the task, please feel free to assign it to me.

**Comment by indyfromoz** [comment]
Hi @kasem-sm Thank you for merging my PR. Can you please add the `hacktoberfest-accepted` label to the issue? This will help count my contributions towards Hacktoberfest.

**Comment by kasem-sm** [comment]
> Hi @kasem-sm Thank you for merging my PR. Can you please add the `hacktoberfest-accepted` label to the issue? This will help count my contributions towards Hacktoberfest.

Done :)
