### ISSUE TITLE
Getting "Special characters are not allowed" while entering username with space at end in Register Screen

### ISSUE THREAD

**Issue by rvenky125** [kasem-sm/SlimeKT#190]
By clicking on the register with a username having space at the end I'm getting this message in Snackbar. I think the text is not trimmed on validation. I'm passing my opinion here that may not be correct. I'm thinking that how it would be if we auto remove the special characters (or) Spaces entered while typing by showing an info msg in Snackbar.

**Comment by kasem-sm** [comment]
Hi. You are right. Gotta fix this asap.

**Comment by rvenky125** [comment]
Okay, I'll take it

**Comment by rvenky125** [comment]
Hello, the password filed accepting white spaces(I mean in between the letters), is it intended by you? I'm willing to change this behavior

**Comment by kasem-sm** [comment]
It is a bug. Yes, you can create a PR.

**Comment by rvenky125** [comment]
Okay
