### ISSUE TITLE
Migrate SlimeKT's backend to any other platform as Heroku is closing it free dynos

### ISSUE THREAD

**Issue by kasem-sm** [kasem-sm/SlimeKT#204]
Ref: https://twitter.com/FrancescoCiull4/status/1563084661609623559

**Comment by Meghdut-Mandal** [comment]
Fly.io is the simplest alternative to Heroku

**Comment by kasem-sm** [comment]
Thanks for letting me know. This issue is on my Todo list. Will do it asap

**Comment by kasem-sm** [comment]
Slime KT server is live on Railway.app
