### ISSUE TITLE
Please put a download link to release APK. Existing link not working (404)!

### ISSUE THREAD

**Issue by unaisulhadi** [kasem-sm/SlimeKT#95]
![Screenshot 2022-04-22 195743](https://user-images.githubusercontent.com/28825858/164734873-41c9b59a-4121-423e-b4f5-e773d83c0676.png)

**Comment by kasem-sm** [comment]
Hey @unaisulhadi, 
Thanks for pointing out, I'll update the link.

You can currently get the latest APK from the release page or from here, https://github.com/kasem-sm/SlimeKT#latest-release 

![image](https://user-images.githubusercontent.com/83884225/164737262-a4a293ec-93f4-478c-82f8-8ffad9d18f28.jpeg)
